### ISSUE TITLE
Error using ES6 destructuring / rest parameters

### ISSUE THREAD

**Issue by nevcos** [bluetech/ng-annotate-patched#2]
When using ES6 destructuring *ng-annotate-patched* is giving the following errors:

## destructuring on variables

**Example:**
```
function(r) {
  var {a,b} = r;
}
```

**Error:**
```
ERROR in ./Test.js
Module build failed: Error: StringMap expected string key
    at stringmap.set (.\node_modules\stringmap\stringmap.js:99:19)
    at Scope.add (.\node_modules\ng-annotate-patched\build\es5\scope.js:103:17)
    at .\node_modules\ng-annotate-patched\build\es5\scopetools.js:38:25
    at Array.forEach (native)
    at Object.createScopes [as pre] (.\node_modules\ng-annotate-patched\build\es5\scopetools.js:36:27)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:11:43)
    at Object.base.Program.base.BlockStatement (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:195:5)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.skipThrough (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:183:37)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.base.ScopeBody (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:288:50)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.base.Function (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:284:3)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.base.FunctionDeclaration (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:262:60)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.skipThrough (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:183:37)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.base.AssignmentExpression.base.AssignmentPattern (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:353:3)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.skipThrough (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:183:37)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.base.ExpressionStatement.base.ParenthesizedExpression (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:201:35)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.skipThrough (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:183:37)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.base.Program.base.BlockStatement (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:195:5)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at traverse (.\node_modules\ng-annotate-patched\build\es5\traverse.js:16:7)
    at Object.setupScopeAndReferences (.\node_modules\ng-annotate-patched\build\es5\scopetools.js:18:5)
```

## destructuring on function parameters

**Example:**
```
function([a,b]) {}
function({a,b}) {}
```

**Error:**
```
ERROR in ./Test.js
Module build failed: Error: StringMap expected string key
    at stringmap.set (.\node_modules\stringmap\stringmap.js:99:19)
    at Scope.add (.\node_modules\ng-annotate-patched\build\es5\scope.js:103:17)
    at .\node_modules\ng-annotate-patched\build\es5\scopetools.js:65:25
    at Array.forEach (native)
    at Object.createScopes [as pre] (.\node_modules\ng-annotate-patched\build\es5\scopetools.js:64:21)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:11:43)
    at Object.base.MemberExpression (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:371:3)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.skipThrough (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:183:37)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.base.NewExpression.base.CallExpression (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:361:3)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.skipThrough (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:183:37)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.base.NewExpression.base.CallExpression (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:367:9)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.skipThrough (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:183:37)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.base.MemberExpression (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:371:3)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.skipThrough (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:183:37)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.base.NewExpression.base.CallExpression (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:361:3)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.skipThrough (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:183:37)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.base.ReturnStatement.base.YieldExpression.base.AwaitExpression (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:228:24)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
    at Object.skipThrough (.\node_modules\ng-annotate-patched\node_modules\acorn\dist\walk.js:183:37)
    at c (.\node_modules\ng-annotate-patched\build\es5\traverse.js:13:41)
```

## Cause

On both scenarios the `node.$scope.add` is being called with name as `undefined`, causing an Error.
This is because accessing the element's name on both scenarios is different then what is implemented for the simpler scenarios (variable and parameters).

## Possible fixes

Either add a `try/catch` or do not calling `node.$scope.add` when the name is not defined.

**Comment by nevcos** [comment]
@bluetech I've created an PR - https://github.com/bluetech/ng-annotate-patched/pull/3 - with a fix proposal, please review it.
Thanks!

**Comment by bluetech** [comment]
Thanks for the report & PR.

Could you create a complete js file which reproduces the issue? Just trying the snippets above, I am not able to reproduce.

**Comment by nevcos** [comment]
@bluetech you're right, the property value shorthand scenario is not a problem, I did a mistake.
But for destructuring I was able to reproduce with 2 simple tests (with variable and with parameter):

```
module.exports = Test;
/** @ngInject */
function Test($log) {
  this.$log = $log;
}
// This gives error
Test.prototype.destructuringTest1 = function () {
  const {a,b} = {a:1, b:2};
};
// This gives error
Test.prototype.destructuringTest2 = function ([a,b]) {
  return a + b;
};
// This is OK
Test.prototype.propertyShorthandTest3 = function (a,b) {
  return {a,b};
};
```

I'll remove the *object literal property value shorthand* scenario from this issue.
